### ISSUE TITLE
Add dynamic HEC metadata support based on record Introspection

### ISSUE THREAD

**Issue by dtregonning** [splunk/kafka-connect-splunk#138]
Customers are looking to add custom source, sourcetype, host to HEC payloads based of a field or value stored within a Kafka Message.

We should add-support for dynamic HEC meta-data.

**Comment by hire-vladimir** [comment]
would be neat to also specify special _semi-static_ fields, ie **splunk_kafka_processor_server** that would default to the node name that processed the read event from the bus. This is very handy when it comes to troubleshooting/understanding load balancing/work distribution & issue tracking.

**Comment by dtregonning** [comment]
fixed in #168
