### ISSUE TITLE
hasTrustStorePath is always set to true

### ISSUE THREAD

**Issue by dkulig** [splunk/kafka-connect-splunk#149]
```hasTrustStorePath``` is always set to  ```true``` because ```StringUtils.isNotBlank``` is called on ```SSL_TRUSTSTORE_PATH_CONF``` which is only a configuration property name. 

https://github.com/splunk/kafka-connect-splunk/blob/c236d478b10fc93afc5eb6919ca25d609234b199/src/main/java/com/splunk/kafka/connect/SplunkSinkConnectorConfig.java#L190

Should be:

```hasTrustStorePath = StringUtils.isNotBlank(trustStorePath); ```

**Comment by dontregonning** [comment]
@dkulig - Thank you for reporting the issue. i agree, definitely incorrect. Cheers

**Comment by dtregonning** [comment]
#150 fixed
