### ISSUE TITLE
Develop set of dashboards to monitor connector health

### ISSUE THREAD

**Issue by hire-vladimir** [splunk/kafka-connect-splunk#155]
Kafka/JMX exposes loads of interesting metrics to understand the sink behavior. This is documented at https://kafka.apache.org/documentation/#monitoring

Would be great to Splunk this data to provide set of performance and health related dashboards on key metrics. This effort will pave the way of better opportunity for full end to end data processing visibility and dynamic node scaling.

**Comment by chenziliang** [comment]
You can use Splunk Kafka AddOn to collect JMX data
