### ISSUE TITLE
AMQ Streams

### ISSUE THREAD

**Issue by sayeedc** [splunk/kafka-connect-splunk#187]
Does the Splunk Kafka Connect run work with different flavours of Kafka such as Redhat's AMQ Streams? 

https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/html-single/using_amq_streams_on_openshift_container_platform/index#kafka-connect-str

**Comment by dtregonning** [comment]
Hi @sayeedc - Splunk Connect for Kafka is a connector built on top of the Kafka Connect Framework which is referenced in the link you provided. As part of your AMQ Stream setup as long as you implement the Kafka Connect cluster component you will be able to deploy the Splunk Connector to send events to Splunk.
