### ISSUE TITLE
Upgrade Documentation

### ISSUE THREAD

**Issue by MattUebel** [splunk/kafka-connect-splunk#189]
I'm planning out the upgrade of the connector from 1.0 to the current release. My guess is that the connector can be upgraded one host at a time, but I wanted to find any caveats or existing documentation first.

There doesn't appear to be any documentation on upgrading, at least none that I could find here : https://docs.splunk.com/Documentation/KafkaConnect/1.1.1/User/InstallSplunkKafkaConnect

**Comment by MattUebel** [comment]
👋 any update on this? I'm hoping to move forward with the upgrade this week.

**Comment by MattUebel** [comment]
🙏

**Comment by MattUebel** [comment]
Hi @dtregonning , I'm going to make a run at upgrading next week. I'd like to phase it in, upgrading a single instance of the connector and baking it in before we move to the rest.

If we had that backoff interval configuration set in the cluster config stored in kafka, will the other connectors care?

Or do they all need to be on the new version before updating the config in the kafka topic?

Thanks! 🙏

**Comment by chaitanyaphalak** [comment]
just in case someone's looking for it, https://docs.confluent.io/current/connect/managing/upgrade.html

**Comment by chaitanyaphalak** [comment]
fixed as part of https://github.com/splunk/kafka-connect-splunk/releases/tag/v2.0
