### ISSUE TITLE
Offsets not committed when consuming pre-formatted HEC events

### ISSUE THREAD

**Issue by hubert-s** [splunk/kafka-connect-splunk#196]
We monitor consumer lag using burrow.  While data flows correctly, we noticed that offsets do not get committed when using the following combination:

- splunk.hec.json.event.formatted=true
- splunk.hec.raw=false

Whenever the kafka connector restarts, there is the potential for duplicate events to be POST-ed into the event endpoint.

It looks like in `SplunkSinkTask.createHecEventFrom`, a `JsonEvent` is created but the `SinkRecord` is never tied to it.  Without the `SinkRecord`, the `KafkaRecordTracker` object does not emit any offsets to be committed.

**Comment by dtregonning** [comment]
Thanks @hubert-s for reporting, will test out and include in next update.

**Comment by moreda** [comment]
@hubert-s , thanks a lot for raising and solving this. I've just reached on my own to the same exact patch ... after several hours of spelunking and just before finding this issue 😊. At least this could serve as "it works for me as well".
Thanks to @dtregonning too, of course, and kudos for the great work!

**Comment by chaitanyaphalak** [comment]
Merged as part of https://github.com/splunk/kafka-connect-splunk/pull/230
Thanks for the collaboration @moreda @hubert-s
