### ISSUE TITLE
Need regex support for topic names

### ISSUE THREAD

**Issue by sarakavi** [splunk/kafka-connect-splunk#198]
Currently comma separated list is supported but I'm looking for regex in the topic name

**Comment by dtregonning** [comment]
Hi @sarakavi - agreed it would be great to capture all the topics based on a regex and ingest them to Splunk.
We would need to refactor the way we handle the mappings of 
n kafka topics -> n splunk indexers.

So unfortunately not currently supported but potentially something we can do at a later date.

**Comment by chaitanyaphalak** [comment]
implemented as part of https://github.com/splunk/kafka-connect-splunk/pull/283
please open a new issue, if you have something else to address
