### ISSUE TITLE
how to custom consumer groupId 

### ISSUE THREAD

**Issue by weishengmin** [splunk/kafka-connect-splunk#199]
when i use this ,the consumer groupId is "connect-kafka-connect-splunk " , how to config groupId which i want

**Comment by dtregonning** [comment]
Hi @weishengmin - The consumer groupid will be set based on the `name` param used when deploying the connector. Check out the description for name as part of the required-parameters section of the Readme
https://github.com/splunk/kafka-connect-splunk#required-parameters

**Comment by weishengmin** [comment]
@dtregonning 
thank you very much
