### ISSUE TITLE
Connector breaks after one site in multi site cluster is down

### ISSUE THREAD

**Issue by jamie00170** [splunk/kafka-connect-splunk#202]
When consuming data from Kafka and sending to a multi site indexer cluster, if one of the sites in the indexer cluster goes down then the Kafka tasks almost completely stop processing data. 

Each task does the following in a continuous loop (simplified considerably):

1. Get some Kafka Records via a call to KafkaConsumer.poll()
2. If the number of records are enough to fill the maximum batch size or the flush interval has been reached -> create a event batch from the records else go back to step one to get more records
3. If there are any "failed batches" attempt to send them first in a loop
3.1 If the task receives an error when sending the batch place the batch back in the list of failed batches else remove it from list of failed batches
3.2 Mark the indexer as having "back pressure" resulting in the LB not choosing this indexer to send another batch to for the next 60 seconds ( now configurable) 
4. Attempt to send the created batch of events to an indexer decided by load balancer
4.1 if the task receives an error then place the batch in the list of failed batches and mark the indexer as having back pressure

If an indexer is down when a task attempts to send a batch of events the connection times out (after around a minute), each time the task tries to send a batch to a indexer which is down it doesn't process any data for around a minute. This is enough to seriously impact the throughput of the tasks depending on the percentage of indexers that have gone down.  

If half (or any significant percentage) of the indexers are down then the list of failed batches will build up, now when the task comes to step 3 above then, for example, say there are 10 failed batches in the list, if the task attempts to send these failed batches to the indexers that are down then the task can spend up to 10 minutes in that loop (by the time it gets out of the loop 9/10 of the indexers will no longer be marked as having back pressure so the load balancer can choose to send data to them again). This in an obvious problem for throughput but in addition to that, if the tasks spends longer in this loop than the configured time for "max.poll.interval.ms" (default is 5 minutes) then a re-balance will be triggered since the task hasn't polled for any data in the last 10 minutes. 

When the task comes to commit it's offsets (for the batches it has eventually sent) it will receive a "CommitOffsetException" since the group has already re-balanced which means it won't be able to update it's position in the log so the new task which has been assigned the partitions will send the same events to Splunk again.  (This will situation will likely continue in a loop depending on the percentage of indexers that are down).

Potential Solutions

At the moment if one of our indexer cluster sites were to go down we would have to do a rolling update to our connector configurations to remove the indexers in the downed site from the load balancer which can take around 90 minutes, we currently have around 100 connectors in production. This isn't ideal especially if this happens out of hours, it could take several hours for us to fix the connectors. 
 
It would be good if we could detect when an indexer is down and permanently remove it from the load balancer. 

One potential solution for this is to have a background thread that runs every few minutes and checks whether a connection can be established to each indexer on the HEC port, if no connection can be established remove it from the load balancer with a configurable timeout before checking if that indexer is alive again. 

We could also just check for Connection timeout errors and mark that indexer as down for a considerable period of, this is probably easier to implement and has less impact on CPU usage but I think it is sub-optimal in that we still would have a period of very low throughput before all of the indexers have been marked as down.

**Comment by jamie00170** [comment]
The time taken to perform a rolling update to all connectors should decrease significantly once we upgrade to version 2.3.0 of Kafka due to the new co-operative re-balances, however, it would still be nice for the Splunk Sink tasks to be able to handle the failure of one site.

**Comment by chaitanyaphalak** [comment]
Closed as part of https://github.com/splunk/kafka-connect-splunk/pull/243
