### ISSUE TITLE
After an org.apache.http.NoHttpResponseException the connector don't recover.

### ISSUE THREAD

**Issue by FranciscoGualdi** [splunk/kafka-connect-splunk#203]
After received an **org.apache.http.NoHttpResponseException** the connector can't recover from that state and the next attempts to push message results in **com.splunk.hecclient.HecException: All channels have back pressure**.

This behavior happens after a while. Changing the setting **splunk.hec.http.keepalive=false** look like fixed the issue. But I'm not confident if this is the best approach to solve.

Did anyone experience something similar?

**Comment by jamie00170** [comment]
Hi Franciso, 

Are you using version 1.1.1? There's a bug which means your indexers will be marked as having back pressure for a very long time after you receive an noHttpResponseException (Fixed here: https://github.com/splunk/kafka-connect-splunk/pull/191 but it's not been included in a release yet as far as I know). There's no work around at the moment unfortunately so I'd suggest you use an earlier version. 

Thanks, 

Jamie
