### ISSUE TITLE
Make flush window configurable 

### ISSUE THREAD

**Issue by jamie00170** [splunk/kafka-connect-splunk#204]
Through testing I've found that increasing the batch size increases the throughput of the task, in the case where we have large batch sizes or very low volume Kafka topics (if we use a Kafka topic for alerting) where we don't set the batch size to 1 we may want to decrease the flush interval from 30 seconds.

**Comment by chaitanyaphalak** [comment]
Closed as part of https://github.com/splunk/kafka-connect-splunk/pull/224
