### ISSUE TITLE
Event limit enforced even when not using acks which can reduce throughput x20 

### ISSUE THREAD

**Issue by jamie00170** [splunk/kafka-connect-splunk#205]
Currently the max.outstanding.events parameter limits the number of events that can be in memory before they have been acknowledged which seems to work as intended when using acknowledgements.

However when we aren't using acknowledgements we don't need to store the events in memory after a 200 response has been received from Splunk, we just need to know the offsets so they can be committed. Once a 200 response has been received and we aren't using acknowledgements then we assume the events in the batch have been indexed so we will never send the events again. For this reason we don't need to keep the events in memory until the offsets are committed. 

My understanding of the way the Kafka Record Tracker works when not using acks is:

1. Each event batch that is created is added to the tracker just before it is passed from the SplunkSinkTask to the HEC client to be sent.
2. The only way for an event batch to be removed from the tracker is during the execution of the computeOffsets method in the KafkaRecordTracker class, all batches that have status of committed are removed.
3. At the start of the put method in SplunkSinkTask a check is performed to determine if the max number of outstanding events have been reached i.e. is the number of events in the tracker more than or equal to the number of max outstanding events defined in the connector. If this is the case then a RetriableException is thrown which instructs the SinkTask to pause the Kafka consumer.
4. The computeOffsets method is only called at an interval defined by "offset.flush.interval.ms" in the connect distributed properties file. The Sink task calls the preCommit method at this interval which is overridden by the preCommit method in the SplunkSinkTask which results in the computeOffsets method executing. 
5. The default value of max.out.standing.events is 1,000,000 which means the Kafka consumer of the task is paused when either 1,000,000 events are in the tracker or 100,000 failed events are in the tracker (10%) through a RetriableException being thrown.
6. The default value of offset.flush.interval.ms is 60000 (60 seconds) so the . 

Given this, each task is limited to processing one million events every 60 seconds. In our case, we had set the max.outstanding.events to be 100,000 (to limit the memory usage since we have 148 indexers and each destination adds memory requirement, I'll create a separate issue to discuss this ) and offset.flush.interval to 10 seconds. This means each task we have is limited to processing 100,000 events every 10 seconds which significantly impacts the throughput. What we observe is that the task processes events for a few seconds then the max.outstanding.events is reached and has to pause until the 10 second interval is reached and the offsets are committed. This removes the events from the tracker, freeing up space for more events to be processed and allows the events to be removed from memory. 

I was able to increase the throughput of a task from 2386 EPS to 11292 EPS just by increasing the max outstanding events from 100,000 to 500,000. However, this increases the memory usage since all of the 500,000 events are now stored in memory until the 10 second interval is reached. If we decrease offset.flush.interval to 5 seconds (from 10 seconds) then the EPS increases to 38009 since the max outstanding events is never reached because the tracker is cleared every 5 seconds. 

As described above, by changing certain parameters we can achieve expected throughput however, this comes at the cost of greatly increased memory usage. I believe this could be avoided if we remove the batch from the tracker once a 200 response is received from the Splunk HEC.

For users leaving the default settings (1,000,000 events processed every 60 seconds) they will run into throughput issues when consuming from high volume topics which generally results in the users increasing the number of tasks unnecessarily.

**Comment by jamie00170** [comment]
Even when using acknowledgements, I think it would be preferable to remove the batch of events from the tracker when it is acknowledged instead of waiting for the offset.flush.interval.ms (which could be up to 60 seconds). I don't think we need to keep track of the events after they have been acknowledged, just the offsets.

**Comment by chaitanyaphalak** [comment]
This issue is addressed as part of https://github.com/splunk/kafka-connect-splunk/pull/237
