### ISSUE TITLE
can't find $kafka_home$/bin directory

### ISSUE THREAD

**Issue by lx277856602** [splunk/kafka-connect-splunk#208]
where is the bin directory?

cd splunk/etc/kafka-connect-splunk-1.1.1
[root@splunk42-001 kafka-connect-splunk-1.1.1]# ls -l
total 71324
-rwxr-xr-x  1 root root     2758 May  3  2019 build.sh
drwxr-xr-x  2 root root     4096 May  3  2019 ci
drwxr-xr-x  2 root root     4096 Jan  2 18:28 config
-rw-r--r--  1 root root     7229 Jan  5 09:51 dependency-reduced-pom.xml
-rw-r--r--  1 root root     3715 May  3  2019 kafka-connect-splunk.iml
-rw-r--r--  1 root root    11357 May  3  2019 LICENSE
-rw-r--r--  1 root root    12662 Dec 21 12:36 pom.xml
-rw-r--r--  1 root root    12656 Dec 21 12:36 pom.xml.versionsBackup
-rw-r--r--  1 root root    18105 May  3  2019 README.md
-rw-r--r--  1 root root 62416198 Jan  5 11:16 splunk-kafka-connect-dev.tar.gz
-rw-r--r--  1 root root       45 Jan  2 18:25 splunk-kafka-connect.tar.gz
-rw-r--r--  1 root root 10513644 Dec 21 10:58 splunk-kafka-connect-v1.1.1.jar
drwxr-xr-x  4 root root     4096 May  3  2019 src
drwxr-xr-x 10 root root     4096 Jan  5 09:51 target

**Comment by chaitanyaphalak** [comment]
the jar is in the target folder.
