### ISSUE TITLE
support for splunk.header.time

### ISSUE THREAD

**Issue by MattUebel** [splunk/kafka-connect-splunk#210]
It's great that we can map record headers to splunk meta field, but `time` is missing.

**Comment by MattUebel** [comment]
created splunk idea here https://ideas.splunk.com/ideas/APPSID-I-10

**Comment by chaitanyaphalak** [comment]
@MattUebel are you referring to the timestamp in the Kafka record header or you want to use your own header?

**Comment by MattUebel** [comment]
:wave: @chaitanyaphalak , that'd be the kafka record header! thanks!

**Comment by chaitanyaphalak** [comment]
Is the time in your kafka header of the following format? 

"time" | The event time. The default time format is epoch time format, in the format <sec>.<ms>. For example, 1433188255.500 indicates 1433188255 seconds and 500 milliseconds after epoch, or Monday, June 1, 2015, at 7:50:55 PM GMT.

reference - https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/FormateventsforHTTPEventCollector#Event_metadata

**Comment by chaitanyaphalak** [comment]
@MattUebel can you provide more information based on the above comment?

**Comment by MattUebel** [comment]
we haven't actually had any records populated with custom headers for time, source, sourcetype, index, host etc.

This would likely follow the same pattern as 

```
   "splunk.header.index": "<header-value-to-be-used-as-splunk-index>",
   "splunk.header.source": "<header-value-to-be-used-as-splunk-source>",
   "splunk.header.sourcetype": "<header-value-to-be-used-as-splunk-sourcetype>",
   "splunk.header.host": "<header-value-to-be-used-as-splunk-host>",
```

and, yup, we would probably use epoch if possible for the time format

**Comment by rockb1017** [comment]
Hello, @MattUebel 
I don't think using header for time is a good approach because it would negatively impact the performance. 
You can follow HEC event format just like the reference @chaitanyaphalak provided. 
reference - https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/FormateventsforHTTPEventCollector#Event_metadata

or you can ingest it to raw endpoint instead and use props.conf and transform.conf to pick up timestamp from a specific key.
https://community.splunk.com/t5/Getting-Data-In/Defining-Timestamp-for-HEC-Input/m-p/413430#M73140

**Comment by fwijnholds** [comment]
@rockb1017 we have frustrated customers for this feature to worrk as is. The  INGEST_EVAL is working if we have but a single source. With multiple sourcetypes we have failing extractions.

**Comment by rockb1017** [comment]
I can understand the issue. one thing to clarify, having time in the `header` is not right way in our connector. 
We have it in our roadmap to extract the time from record. I don't know when we will get to it. If community can contribute, we will definitely review and merge.
