### ISSUE TITLE
Splunk connect keeps retrying after getting Invalid data format error

### ISSUE THREAD

**Issue by alamzeeshan** [splunk/kafka-connect-splunk#215]
Splunk Connect keeps on retrying after getting **Invalid data format error**. It is of no use as Splunk is never going to accept these invalid data so even if it attempts to send the same batch million times it will still get rejected. There should be an option to ignore these Invalid data instead of retrying again and again. Because of this Kafka connect gets OOM Exception and it fails.

```
Mar 30 10:01:06  connect-distributed[10185]: [2020-03-30 10:01:06,580] WARN attempting to resend batch 2ee22cee-e4fe-48ac-9e85-f73b63f1e95c with 500 events, this is attempt 1724 out of -1 for this batch  (com.splunk.kafka.connect.SplunkSinkTask:139)
Mar 30 10:01:07  connect-distributed[10185]: [2020-03-30 10:01:07,815] ERROR failed to post events resp={"text":"Invalid data format","code":6,"invalid-event-number":30}, status=400 (com.splunk.hecclient.Indexer:180)
```

**Comment by rockb1017** [comment]
Hello,

please tell us more about your environments? (your HEC config and connector config)
and could this be related? https://github.com/splunk/kafka-connect-splunk/issues/193#issuecomment-505557578

**Comment by alamzeeshan** [comment]
I have already gone through [#193 (comment)](https://github.com/splunk/kafka-connect-splunk/issues/193#issuecomment-505557578) . It is unrealated. For me most of the messages are being received by splunk. For some of the messages it is saying **Invalid data format error**.

Splunk Version **7.0.4**

Confluent Kafka Connect **5.4.0**

Connector details:

`{
	"name": "kc-ws-prd-splunk",
	"config": {
		"connector.class": "com.splunk.kafka.connect.SplunkSinkConnector",
		"tasks.max": "12",
		"splunk.indexes": "wi_containers",
		"topics": "mykafkatopic",
		"splunk.hec.uri": "http://xxx.xxx.com:80",
		"splunk.hec.token": "xxxxxxxxxxxxx",
		"splunk.hec.ssl.validate.certs": false,
		"splunk.hec.event.timeout": "120",
		"splunk.hec.ack.enabled": false
	}
}`

**Comment by chaitanyaphalak** [comment]
@alamzeeshan for the OOM case we need to investigate more. I think there might be an opportunity to improving the retry strategy.

**Comment by alamzeeshan** [comment]
We have increased the heap size for kafka connect from the the default `-Xms256M -Xmx2G` to  -`Xms6G -Xmx6G`. AFter that we haven't encountered OOM. Our event size is approx 2KB each and the default value for `splunk.hec.max.outstanding.events` is `1000000`. So maybe because of so many outstanding events in memory was triggering OOM.

**Comment by alamzeeshan** [comment]
But this still doesn't resolves the original issue of  **Invalid data format error**

`Mar 30 10:01:07  connect-distributed[10185]: [2020-03-30 10:01:07,815] ERROR failed to post events resp={"text":"Invalid data format","code":6,"invalid-event-number":30}, status=400 (com.splunk.hecclient.Indexer:180)`

I don't control the data coming to kafka. Ideally the invalid data should be dropped by splunk connector and the data should be logged someplace so that we can know what was the invalid data.

**Comment by chaitanyaphalak** [comment]
@alamzeeshan you can remove that topic from the connector too. Is that a good option? Anyways you don't want to index that data to splunk, so why include that topic? Or is it that a topic has different types of data coming in?

**Comment by chaitanyaphalak** [comment]
@alamzeeshan were you able to resolve the issue? can you provide a sample record that's being rejected?
Have you tried using splunk.hec.max.retries config?
Thanks

**Comment by alamzeeshan** [comment]
@chaitanyaphalak I don't have the sample record as it was coming from Kafka which had millions of records in json format. I didn't had any way to figure out which record was invalid as splunk-connect was not logging it anywhere. The only information in the log was `ERROR failed to post events resp={"text":"Invalid data format","code":6,"invalid-event-number":30}, status=400 (com.splunk.hecclient.Indexer:180)`. 

The config `splunk.hec.max.retries` was left to default which I believe was unlimited retries.

I had to restart the splunk-connect with a new kafka consumer group with latest offset to skip the records which splunk was unable to read.

**Comment by chaitanyaphalak** [comment]
@alamzeeshan you can remove that topic from the connector too. Is that a good option? Anyways you don't want to index that data to splunk, so why include that topic? Or is it that a topic has different types of data coming in?

**Comment by chaitanyaphalak** [comment]
fixed as part of https://github.com/splunk/kafka-connect-splunk/pull/242
