### ISSUE TITLE
SSL misconfiguration appears as runtime org.apache.http.NoHttpResponseException

### ISSUE THREAD

**Issue by gharris1727** [splunk/kafka-connect-splunk#221]
By default, `splunk.hec.ssl.validate.certs` is `true`, and `splunk.hec.ssl.trust.store.path` is empty. This should be an illegal configuration, because SSL certs can never be successfully validated against an empty trust store.

Steps to reproduce:
Use a `splunk.hec.uri` beginning with `https://`
Use the default values for `splunk.hec.ssl.validate.certs` and `splunk.hec.ssl.trust.store.path`
Create a connector with the above configuration properties.

Expected result:
The connector throws a `ConfigException` explaining that `splunk.hec.ssl.trust.store.path` is required when `splunk.hec.ssl.validate.certs = true`.

Actual result:
During connector execution, requests fail with
`org.apache.http.NoHttpResponseException: <address> failed to respond`, triggering back pressure behavior and retries. The connector never writes any records, but never fails either.

**Comment by chaitanyaphalak** [comment]
Fixed as part of https://github.com/splunk/kafka-connect-splunk/pull/238
