### ISSUE TITLE
Consuming from ACL-protected Kafka Topics

### ISSUE THREAD

**Issue by TheRyanMiller** [splunk/kafka-connect-splunk#234]
My Kafka topic has an ACL protecting it from unauthorized consumers. In order to consume this topic, an SSL connection must be established via a client who presents a certificate bearing an authorized "CN" (common name). 
I have searched a bit through the Splunk Connect for Kafka docs and have not seen any mechanism on how I can supply it the cert/key it needs in order to read from my protected topic. Is this possible?

**Comment by gp510** [comment]
@TheRyanMiller - Have you added the cert to the truststore (https://docs.splunk.com/Documentation/KafkaConnect/latest/User/SecurityConfigurations)?
