### ISSUE TITLE
protobuf ingestion support

### ISSUE THREAD

**Issue by MattUebel** [splunk/kafka-connect-splunk#240]
being able to read in records in the protobuf format would be a great feature for us

**Comment by chaitanyaphalak** [comment]
Hey @MattUebel can you explain more?
Are you talking about adding support for io.confluent.connect.protobuf.ProtobufConverter ?

**Comment by MattUebel** [comment]
Essentially, the ability to have the connector consume protobuf encoded topics.

This is already supported? And just a matter of configuring the worker itself with the appropriate schema to decode the protobufs?

**Comment by chaitanyaphalak** [comment]
oh I guess you mean whether the connector natively deserializes protobuf messages?
The connector doesn't support that, yet.

**Comment by MattUebel** [comment]
>oh I guess you mean whether the connector natively deserializes protobuf messages?

Yup! That sounds about right!

Would an ideas.splunk.com and/or support P4 help prioritize this? It would be a huge boon to us 😄

**Comment by chaitanyaphalak** [comment]
@MattUebel contacting support will definitely work :)

**Comment by MattUebel** [comment]
👋 @chaitanyaphalak , I created support case #1858946 to go along with this issue!

**Comment by bluedog13** [comment]
The Confluent managed version of the connector is able to read data from topics that are serialized using PROTOBUF.

**Comment by foram-splunk** [comment]
This issue is resolved in #341
