### ISSUE TITLE
timestamp issue

### ISSUE THREAD

**Issue by giotto69** [splunk/kafka-connect-splunk#241]
Hello everybody
we are producing events in kafka already formatted for HEC, like the following

{"time": "1596212700.000","host":"host-01","source":"bu","fields":{"hn":"hostname1","CLASS":"class1","cust_id":"000013934","category":"IFdata","ifname":"LoopBack7","IFdata.Bits received":"0","IFdata.Bits sent":"0"}}

 so the connector is configured with:
- "splunk.hec.json.event.formatted": true
- "splunk.hec.raw" : false

What we see in Splunk is that the timestamp that we have in the event is ignored, and replaced by "someone"
I don't know who actually is that "someone" but I think it's the "kafka-connect-splunk" that replaces the timestamp with the time the event is being sent to splunk

How can we keep the original timestamp?

thank you in advance

**Comment by rockb1017** [comment]
Hello @giotto69 
Let me confirm with my team and get back to you! thank you.

**Comment by rockb1017** [comment]
Could you check to see any error logs from splunk connector? I am particularly looking to see if there is any logs like "event does not follow correct HEC pre-formatted format: "

**Comment by guilhemmarchand** [comment]
@giotto69 

Unless I am wrong the HEC format is incorrect, it should "event" not "fields", like:

```
{
    "time": 1437522387,
    "host": "dataserver992.example.com",
    "source": "testapp",
    "event": { 
        "message": "Something happened",
        "severity": "INFO"
    }
}
```

https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/FormateventsforHTTPEventCollector

(look for Here's an example of including a JSON object as the event data within a properly-formatted event)

Guilhem

**Comment by giotto69** [comment]
Hello
thank you!
!!!First: I didn't mention that I'm ingesting kpis into metrics indexes :)

I don't see errors relevant to HEC format.
All the HEC formats suggested in documentation are quite confusing for me; anyway using the HEC directly (let's say via curl) works as expected.

In kafka-connect-splunk instead, as per my understanding, there's a trade-off between "raw" and "event" endpoints.
It seems that using "raw" is mandatory to keep the original timestamp. 
Nevertheless in this way I'm not able to use "source" and "host" from the event. In splunk I get dimensions as "extracted.host" and "extracted.source".
So currently I'm using
    "splunk.hec.json.event.formatted": true
    "splunk.hec.raw" : true

Timestamp is ok with the drawback of extracted.host and source.

Giorgio

**Comment by guilhemmarchand** [comment]
@giotto69 

Right I see, it's different then indeed.

To send metrics to Splunk HEC in a native format, you would need to use to the collector endpoint:

https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/Sendmetricstoametricsindex

Therefore, and one could confirm or not my understanding/knowledge, for the moment the sink connector for Kafka Connect does not support the collector endpoint, and cannot then stream metrics to HEC using this method currently, so you have to rely on the raw endpoint and custom index time parsing configuration.

I suppose this might be already in the pipe (having the collector endpoint capability) for a future release.

Guilhem

**Comment by rockb1017** [comment]
Thank you. we will review this and add it into future scope.

**Comment by giotto69** [comment]
Thanks guys!

**Comment by aryznar-splunk** [comment]
Delivered already
