### ISSUE TITLE
Duplicate data in splunk on restart of a splunk connector task

### ISSUE THREAD

**Issue by ashish8678** [splunk/kafka-connect-splunk#263]
We observed that some of the data are getting indexed twice when a task is restarted.
Looks like when a task is restart it is not able to commit the offset for  the data that is sent to splunk which might be causing task to pick the data again.

 Please suggest configuration that can help here.

**Comment by chaitanyaphalak** [comment]
This is expected behaviour, the connector will restart and re-send events for which offsets are not committed.
