### ISSUE TITLE
Sink Connector Error : Unexpected character ('<' (code 60)): expected a valid value

### ISSUE THREAD

**Issue by bluedog13** [splunk/kafka-connect-splunk#277]
I see the below error using the SPLUNK sink connector, when trying to copy messages from a topic into SPLUNK. 

**ERROR failed to parse response payload (com.splunk.hecclient.Indexer:193)
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')**

Below is my configuration for SPLUNK Sink connector

```
"name": "kafka-connect-splunk",
"config": {
    "connector.class": "com.splunk.kafka.connect.SplunkSinkConnector",
    "tasks.max": "3",
    "topics": "mytopic-avro",
    "splunk.hec.uri": "https://myurl:443",
    "splunk.hec.token": "********-****-****-****-********",
    "splunk.hec.ssl.validate.certs": "false"
}

```

Below are the converters defined in connect-distributed.properties file (which also has details about Schema Registry). The messages being written to the topic that follow avro schema defined in the schema registry. AvroSerializer is being used on the producer end. 
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=io.confluent.connect.avro.AvroConverter

However for another connector (a simpler one), which uses the same connect-distributed.properites file, it works just fine. 

```
"name": "my-file-sink",
"config": {
    "connector.class": "org.apache.kafka.connect.file.FileStreamSinkConnector",
    "tasks.max": "3",
    "topics": "mytopic-avro",
    "file" : "my_file_sink_output.txt"
}
```

What is it that I am missing in the SPLUNK Sink connector that is causing the error?

Much appreciated.

**Comment by bluedog13** [comment]
This has been  resolved.  It had nothing to do with the connector but rather parsing of the response from he HEC endpoint.

**Comment by hernanke27** [comment]
@bluedog13, could you please advise how was this issue resolved?. Did you open a ticket to Splunk Support, if so, do you have it for reference ?. 
Appreciate your help.
