### ISSUE TITLE
structured logging for the connector?

### ISSUE THREAD

**Issue by MattUebel** [splunk/kafka-connect-splunk#298]
👋  has anybody setup the connector to log as json, or have any pointers?

It's seems a matter of `log4j` configuration, but that doesn't seem straightforward and so maybe I'm heading in the wrong direction.

**Comment by ankit-splunk** [comment]
@mattuebel  for generating log in JSON format, you need to do some changes in connect-log4j.properties file as below, 
* For generate console log comment out this line `log4j.appender.stdout.layout.ConversionPattern=${connect.log.pattern} `and add below line:  `log4j.appender.stdout.layout.ConversionPattern={"debug_level":"%p","debug_timestamp":"%d{ISO8601}","debug_thread":"%t","debug_file":"%F", "debug_line":"%L","debug_message":"%m"}%n`
* For generate log in file comment out this line `og4j.appender.connectAppender.layout.ConversionPattern=${connect.log.pattern}` and add below line: `log4j.appender.connectAppender.layout.ConversionPattern={"debug_level":"%p","debug_timestamp":"%d{ISO8601}","debug_thread":"%t","debug_file":"%F", "debug_line":"%L","debug_message":"%m"}%n`

**Comment by MattUebel** [comment]
thank you @ankit-splunk , I'll try that!

**Comment by ankit-splunk** [comment]
@MattUebel I think your problem would be resolved using the above solution. so I am closing this issue. If any further questions related to it then reach out.
