### ISSUE TITLE
Event flow stops after running the connector for sometime

### ISSUE THREAD

**Issue by ashish8678** [splunk/kafka-connect-splunk#334]
**Below is the scenario and analysis because of which event processing stops and Kafka offset lag starts increasing.**
When the LinkedBlockingQueue in ConcurrentHec is full below method fails to add new batch to the LinkedBlockingQueue after 1000ms

```
@Override
    public final void send(final EventBatch batch) {
        try {
            batches.offer(batch, 1000, TimeUnit.MILLISECONDS);
        } catch (InterruptedException ex) {
            throw new HecException("failed to offer batch into queue", ex);
        }
    }
```

But at the same time the Records are added to the KafkaRecordTracker.
Since the batch is never sent, the records that were added to the outstanding list of batch in KafkaRecordTracker never gets cleared.
Ultimately the threshold of 1000000 elements reaches which pauses the consumer. Finally it halts the messages flowing down to the splunk unless and until the task are restarted.

**Below are the some to options/solution that can be used here.**

1. Handle case where `batches.offer(batch, 1000, TimeUnit.MILLISECONDS);` return false. Basically clear the tracker if there is failure or the 'offer' method return false or put the batch to the failed batch tracker list.
3. Make timeout of 'offer' method configurable instead of hard coding it to 1000 ms. This will allow user to configure timeout.

**Comment by ashish8678** [comment]
Raised this PR : https://github.com/splunk/kafka-connect-splunk/pull/335 as a fix for the [ISSUE-334](https://github.com/splunk/kafka-connect-splunk/issues/334#issue-1252608568)

**Comment by foram-splunk** [comment]
Closing this issue as #335 is merged. Thanks, @ashish8678.
