### ISSUE TITLE
v2.0.9 - SplunkSinkTaskTest.invalidTimestampFormat() test should set the proper Locale

### ISSUE THREAD

**Issue by aggever** [splunk/kafka-connect-splunk#360]
Hello,

While building the repo with `mvn package`, the `com.splunk.kafka.connect.SplunkSinkTaskTest.invalidTimestampFormat()` Test fails because the `"MM dd yyyy HH:mm:ss.SSS zzz"` timestamp format is not supported in my default Locale.

Setting the default locale to `Locale.ENGLISH` as follow fixes the issue:
```
    @Test
    public void invalidTimestampFormat() {
        ...
        Locale.setDefault(Locale.ENGLISH);
        HecMock hec = new HecMock(task);
        ...
```

If you agree with the above, please consider fixing this for the next release :)

Thanks!

**Comment by VihasMakwana** [comment]
Hii @aggever, can let me know what your default locale is? 
I need to reproduce this in order to apply a fix ;)

Thanks.

**Comment by VihasMakwana** [comment]
Closing as it's inactive for a while. Please reopen if needed
