### ISSUE TITLE
Update Timestamp Extraction description with additional examples  for "timestamp.format"

### ISSUE THREAD

**Issue by revzzver** [splunk/kafka-connect-splunk#382]
The `"timestamp.format"` [parameter description](https://github.com/splunk/kafka-connect-splunk#timestamp-extraction-parameters) does not include any examples for ISO 8601 like timestamps with a 'T' separator for time. Would it be possible to include additional examples such as: 

> If timestamp is `2022-03-29T23:11:52.054`, set timestamp.format to `"yyyy-MM-dd'\''T'\''HH:mm:ss.SSS"`

**Comment by VihasMakwana** [comment]
Closing as PR has been merged
