### ISSUE TITLE
TLS setting for Splunk Sink Connector

### ISSUE THREAD

**Issue by feixuanwo** [splunk/kafka-connect-splunk#397]
Hi,

We want to encrypt the connection between the connector and splunk, how to realize it?
Seems splunk.hec.ssl.validate.certs is the related parameter, but I configured it and met the errors as follows:

ERROR com.splunk.hecclient.LoadBalancer: encountered exception when checking health of indexer Certificate for <IP> doesn't match any of the subject alternative names: [rr-itoa-splunk-i4d-bigdata.de.xxxxx.com], this means indexer and its channels are removed from the loadbalancer

hopes to get some help about this.

Thanks

**Comment by VihasMakwana** [comment]
Okay, so you set `splunk.hec.ssl.validate.certs` to true. and did you add SSL certificates to the the java keystore? 
You also need to set `splunk.hec.ssl.trust.store.path` and `splunk.hec.ssl.trust.store.password`.

For reference, https://stackoverflow.com/questions/4325263/how-to-import-a-cer-certificate-into-a-java-keystore
