### ISSUE TITLE
Add support for timezone override

### ISSUE THREAD

**Issue by gwsales** [splunk/kafka-connect-splunk#398]
When an event comes in with timestamp extraction enabled, we need an option to specify a timezone if the timestamp isn't ISO8601 compliant. 

Example:
```
local_time: 2023-07-26T05:09:50
```
The the timestamp can be used, but without being able to set the specific timezone here we have events showing up with wrong _time values. 

I'm aware the data source should be the ones to fix feed related issues, but timezone is a common issue and should have a way to define or override in this kafka connector.

**Comment by VihasMakwana** [comment]
Will look into this.

**Comment by mo-mosh** [comment]
I have the same issue... and I made a pr
would you @VihasMakwana  review the pr?

**Comment by VihasMakwana** [comment]
Sure

**Comment by mo-mosh** [comment]
Thank you for your help @VihasMakwana

**Comment by VihasMakwana** [comment]
@gwsales can you confirm if the enhancement works in our latest release?

**Comment by VihasMakwana** [comment]
closing this as it has been released
